// NOTE: Assertions have been autogenerated by utils/generate-test-checks.py
// RUN: circt-opt %s -llhd-block-argument-to-select | FileCheck %s

// CHECK-LABEL:   llhd.proc @check_batm(
// CHECK-SAME:                          %[[VAL_0:.*]] : !llhd.sig<i1>) -> (
// CHECK-SAME:                          %[[VAL_1:.*]] : !llhd.sig<i32>) {
// CHECK:           %[[VAL_2:.*]] = llhd.const #llhd.time<0ns, 1d, 0e> : !llhd.time
// CHECK:           %[[VAL_3:.*]] = llhd.prb %[[VAL_0]] : !llhd.sig<i1>
// CHECK:           %[[VAL_4:.*]] = llhd.const 4 : i32
// CHECK:           %[[VAL_5:.*]] = llhd.const 3 : i32
// CHECK:           cond_br %[[VAL_3]], ^bb1, ^bb2
// CHECK:         ^bb1:
// CHECK:           br ^bb3
// CHECK:         ^bb2:
// CHECK:           br ^bb3
// CHECK:         ^bb3:
// CHECK:           %[[VAL_6:.*]] = select %[[VAL_3]], %[[VAL_4]], %[[VAL_5]] : i32
// CHECK:           llhd.drv %[[VAL_1]], %[[VAL_6]] after %[[VAL_2]] : !llhd.sig<i32>
// CHECK:           llhd.halt
// CHECK:         }
llhd.proc @check_batm(%cond : !llhd.sig<i1>) -> (%out : !llhd.sig<i32>) {
  %del = llhd.const #llhd.time<0ns, 1d, 0e> : !llhd.time
  %cond_prb = llhd.prb %cond : !llhd.sig<i1>
  %c1 = llhd.const 4 : i32
  %c2 = llhd.const 3 : i32
  cond_br %cond_prb, ^bb1, ^bb2
^bb1:
  br ^bb3(%c1 : i32)
^bb2:
  br ^bb3(%c2 : i32)
^bb3(%res : i32):
  llhd.drv %out, %res after %del : !llhd.sig<i32>
  llhd.halt
}
