//===- MIRAttributes.td - Moore MIR attribute definitions --*- tablegen -*-===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// Attributes for the Moore MIR dialect. Includable in other dialects.
//
//===----------------------------------------------------------------------===//

#ifndef CIRCT_DIALECT_MOORE_MIR_MIRATTRIBUTES
#define CIRCT_DIALECT_MOORE_MIR_MIRATTRIBUTES

include "circt/Dialect/Moore/MIR/MIRDialect.td"


#endif // CIRCT_DIALECT_MOORE_MIR_MIRATTRIBUTES
