//===- MIROps.cpp - Implement the Moore MIR operations --------------------===//
//
// Part of the LLVM Project, under the Apache License v2.0 with LLVM Exceptions.
// See https://llvm.org/LICENSE.txt for license information.
// SPDX-License-Identifier: Apache-2.0 WITH LLVM-exception
//
//===----------------------------------------------------------------------===//
//
// This file implement the Moore MIR ops.
//
//===----------------------------------------------------------------------===//

#include "circt/Dialect/Moore/MIR/MIROps.h"
#include "circt/Dialect/Moore/MIR/MIRTypes.h"
#include "mlir/IR/Builders.h"
#include "mlir/IR/BuiltinTypes.h"
#include "mlir/IR/PatternMatch.h"
#include "llvm/ADT/SmallString.h"
#include "llvm/ADT/StringExtras.h"
#include "llvm/ADT/TypeSwitch.h"

using namespace circt;
using namespace moore::mir;

//===----------------------------------------------------------------------===//
// TableGen generated logic.
//===----------------------------------------------------------------------===//

// Provide the autogenerated implementation guts for the Op classes.
#define GET_OP_CLASSES
#include "circt/Dialect/Moore/MIR/MIR.cpp.inc"
#include "circt/Dialect/Moore/MIR/MIREnums.cpp.inc"
#include "circt/Dialect/Moore/MIR/MIRStructs.cpp.inc"
